version: 1.2.9

spring:
  profiles:
    active: dev
    include: secret

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  data:
    redis:
      repositories:
        enabled: false