spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${custom.db.url}
    username: ${custom.db.username}
    password: ${custom.db.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: false
      hibernate:
        format_sql: true
        use_sql_comments: true

custom:
  redis:
    host: redis_1
    port: 6379

logging.level:
  org.hibernate.SQL: debug

slack:
  webhook:
    url: ${custom.SLACK_WEBHOOK_PRODUCTION_URL}