spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${custom.url}
    username: ${custom.username}
    password: ${custom.password}
  jpa:
    hibernate:
      ddl-auto: create

custom:
  redis:
    host: redis_1
    port: 6379